modules.json
```
{
params: {
// ...
}
}
```
=> ENG-1369 & ENG-1366 merged tickets

modules.json, modules/tripleliftBidAdapter.js
adds tripleliftBidAdapter.js and adds tripleliftBidAdapter to modules.json
Let me know if this .js file needs to be updated. I gave it a once-over and it looks good.
=> add tripleliftBidAdapter

modules/criteoBidAdapter.js, package-lock.json, package.json, test/spec/modules/criteoBidAdapter_spec.js, webpack.conf.js
```
{
params: {
// ...
}
}
```
=> ENG-1438 - Criteo update per Criteo via Emily

modules.json
```
{
params: {
// ...
}
}
```
=> ENG-1475 - added quantcast bid adapter

modules.json
```
{
params: {
// ...
}
}
```
=> hotfix-33A added

modules.json
```
{
params: {
// ...
}
}
```
=> removed zid added aol

modules.json
```
{
params: {
// ...
}
}
```
=> ENG-2193 - added "pubCommonId" module

modules/ffaBidAdapter.js
```
{
params: {
// ...
}
}
```
=> ENG-2206 - only validate 10% of bids

modules.json
```
{
params: {
// ...
}
}
```
=> added dmx bid adapter

modules/ffaBidAdapter.js
```
{
params: {
// ...
}
}
```
=> 1 % change

modules.json
```
{
params: {
// ...
}
}
```
=> ENG-2755 - added aardvark bid adapter

modules.json, package-lock.json
```
{
params: {
// ...
}
}
```
=> Adding Yieldmo

modules.json
```
{
params: {
// ...
}
}
```
=> Added the right YieldMo adapter

modules.json
```
{
params: {
// ...
}
}
```
=> ENG-4358 - removed consumable

modules.json
```
{
params: {
// ...
}
}
```
=> added mediagrid bid adapter to modules.json file

modules/ffaBidAdapter.js, modules/freestarAnalyticsAdapter.js
```
{
params: {
// ...
}
}
```
=> `Eng 4158 2

modules.json, package-lock.json
Include gpt Pre auction module
=> ENG-7046: ADD gpt pre auction module

modules.json
=> ADD apaxdex and adprime bidders

modules.json
ENG-7246-adding ats adapter to modules
=> ENG-7246-adding ats adapter to modules

modules.json, package-lock.json
=> ENG-7733: ADD intentIQ

modules.json
Adds 3 different modules to Prebid verizonID Neustar Id and FPD enrichment
=> Eng 7977 eng 7423 fpd verizon id modules

modules.json
Add new module for concert bidder
=> ADD concert bidder

modules.json
Bidder adapter already in FAD. Adding back to Prebid.
=> PFG-673: Add sonobi adapter

modules.json
- [x ] New bidder adapter   
```
{
params: {
// ...
}
}
```
=> Pfg 1064 pubfig prebid js add 33 across identity module

modules.json
- [x ] New bidder adapter   
Added permutive to modules.json 
```
{
params: {
// ...
}
}
```
=> added permutiveRtdProvider to modules.json

modules.json
https://freestar.atlassian.net/browse/PFG-1709
Remove parrable identity provider module.
=> PFG-1709 Prebid - Remove parrable module

modules.json
=> S2S-1051: ADD connecId module from yahoo

modules.json
=> S2S-1119: ADD taboola as bidder

modules.json
https://freestar.atlassian.net/browse/PFG-2308
Pubfig: Remove EMX bid adapter from prebid.js
=> PFG-2308 remove emx digital

.editorconfig, modules.json, package-lock.json
Add 33acrossIdSystem module and remove 33across as bidder
=> S2S-1592: ADD 33across module

modules.json
=> ADD id5 to modules

modules.json
=> S2S-1590: ADD rise adapter
